#!/usr/bin/env node

import { access, chmod, mkdir, readFile, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const defaultCatalogPath = join(repoRoot, "profiles", "catalog.json");

export async function loadCatalog(path = defaultCatalogPath) {
  const raw = await readFile(path, "utf8");
  const catalog = JSON.parse(raw);
  validateCatalog(catalog);
  return catalog;
}

export function buildCcrConfig(catalog, profileName) {
  const profile = findProfile(catalog, profileName);
  if (!profile.ccr) {
    throw new Error(`profile "${profileName}" does not define a CCR config`);
  }
  return structuredClone(profile.ccr);
}

export function buildShellSnippet(catalog, profileName) {
  const profile = findProfile(catalog, profileName);
  const shell = profile.shell ?? {};
  const lines = [
    `# Generated by airkit for profile: ${profile.name}`,
    `# ${profile.summary}`,
  ];

  if (shell.ccrTokenOpRef) {
    lines.push(`export CCR_ANTHROPIC_AUTH_TOKEN_OP_REF=${quoteShell(shell.ccrTokenOpRef)}`);
  }

  if (shell.ccrStartFunction) {
    lines.push(
      `${shell.ccrStartFunction}() {`,
      "  CCR_ANTHROPIC_AUTH_TOKEN_OP_REF=${CCR_ANTHROPIC_AUTH_TOKEN_OP_REF:?missing CCR_ANTHROPIC_AUTH_TOKEN_OP_REF} ccr-start \"$@\"",
      "}",
    );
  }

  for (const wrapper of shell.wrappers ?? []) {
    lines.push(`${wrapper.name}() {`);
    for (const [key, value] of Object.entries(wrapper.env ?? {})) {
      lines.push(`  export ${key}=${quoteShell(value)}`);
    }
    lines.push(`  ${wrapper.command} "$@"`, "}");
  }

  return `${lines.join("\n")}\n`;
}

export async function exportOssRelease({ outDir }) {
  if (!outDir) throw new Error("exportOssRelease requires outDir");

  const catalog = await loadCatalog();
  const publicCatalog = {
    schema: catalog.schema,
    profiles: catalog.profiles.filter((profile) => profile.visibility === "public"),
  };

  await mkdir(join(outDir, "src"), { recursive: true });
  await mkdir(join(outDir, "profiles"), { recursive: true });
  const binPath = join(outDir, "src", "airkit.mjs");
  await writeFile(binPath, await readFile(fileURLToPath(import.meta.url), "utf8"));
  await chmod(binPath, 0o755);
  await writeFile(join(outDir, "profiles", "catalog.json"), `${JSON.stringify(publicCatalog, null, 2)}\n`);
  await writeFile(join(outDir, "package.json"), `${JSON.stringify(publicPackage(), null, 2)}\n`);
  await writeFile(join(outDir, "CLAUDE.md"), claudeGuide());
  await writeFile(join(outDir, "README.md"), publicReadme());
}

export function planInstall(catalog, profileName, options = {}) {
  const profile = findProfile(catalog, profileName);
  const configDir = resolve(options.configDir ?? defaultConfigDir());
  const ccrConfig = join(configDir, "ccr", `${profile.name}.json`);
  const shellSnippet = join(configDir, "shell", `${profile.name}.zsh`);

  return {
    profile: { name: profile.name, summary: profile.summary, visibility: profile.visibility },
    write: options.write === true,
    force: options.force === true,
    files: { ccrConfig, shellSnippet },
    nextSteps: [
      `source ${shellSnippet}`,
      `ccr config: ${ccrConfig}`,
      "Run ccr-start, then launch the rendered wrapper from the shell snippet.",
    ],
  };
}

export async function installProfile(catalog, profileName, options = {}) {
  const plan = planInstall(catalog, profileName, options);
  if (!plan.write) return plan;

  await mkdir(dirname(plan.files.ccrConfig), { recursive: true });
  await mkdir(dirname(plan.files.shellSnippet), { recursive: true });
  await writeTextFile(plan.files.ccrConfig, `${JSON.stringify(buildCcrConfig(catalog, profileName), null, 2)}\n`, {
    force: plan.force,
  });
  await writeTextFile(plan.files.shellSnippet, buildShellSnippet(catalog, profileName), { force: plan.force });
  return plan;
}

function findProfile(catalog, profileName) {
  const profile = catalog.profiles.find((candidate) => candidate.name === profileName);
  if (!profile) {
    throw new Error(`unknown profile "${profileName}"`);
  }
  return profile;
}

function validateCatalog(catalog) {
  if (catalog.schema !== 1) throw new Error("catalog schema must be 1");
  if (!Array.isArray(catalog.profiles)) throw new Error("catalog profiles must be an array");

  const seen = new Set();
  for (const profile of catalog.profiles) {
    if (!profile.name || seen.has(profile.name)) throw new Error(`invalid or duplicate profile: ${profile.name}`);
    seen.add(profile.name);
    if (!["internal", "public"].includes(profile.visibility)) {
      throw new Error(`profile "${profile.name}" has invalid visibility`);
    }
    if (profile.ccr) validateCcr(profile.name, profile.ccr);
  }
}

function validateCcr(profileName, ccr) {
  for (const provider of ccr.Providers ?? []) {
    if (typeof provider.api_key === "string" && provider.api_key.startsWith("sk-")) {
      throw new Error(`profile "${profileName}" embeds a secret-looking API key`);
    }
  }
}

function quoteShell(value) {
  return `'${String(value).replaceAll("'", "'\\''")}'`;
}

function publicPackage() {
  return {
    name: "@lzong/ai-runtime-kit",
    version: "0.1.0",
    description: "Public-safe runtime profile templates for AI client wrappers.",
    type: "module",
    bin: { airkit: "src/airkit.mjs" },
    scripts: { check: "node --check src/airkit.mjs" },
    engines: { node: ">=20" },
    license: "MIT",
    author: "LZong, Lim, Un-tiong <lzong.tw@gmail.com>",
  };
}

function publicReadme() {
  return `# ai-runtime-kit

Public-safe runtime profile templates for Claude Code Router and other AI client wrappers.

This repository intentionally contains no private endpoints, no credential-manager item references, and no secret values. Use \`profiles/catalog.json\` as a starting point, then keep machine-specific runtime state outside git.

\`\`\`bash
airkit list
airkit init --profile openai-compatible-example
airkit init --profile openai-compatible-example --write
airkit render ccr --profile openai-compatible-example
airkit render shell --profile openai-compatible-example
\`\`\`

For LLM-guided installation, start with \`CLAUDE.md\`. The normal flow is a dry
run first, then \`--write\` after the user confirms the target paths.
`;
}

async function main(argv = process.argv.slice(2)) {
  const [command, subcommand, ...rest] = argv;
  const catalog = command === "export-oss" ? null : await loadCatalog();

  if (command === "init") {
    const profile = requireFlag([subcommand, ...rest], "--profile");
    const plan = await installProfile(catalog, profile, {
      configDir: readFlag(rest, "--config-dir") ?? defaultConfigDir(),
      force: hasFlag(rest, "--force"),
      write: hasFlag(rest, "--write"),
    });
    process.stdout.write(renderInstallPlan(plan));
    return;
  }

  if (command === "list") {
    const visibility = readFlag(rest, "--visibility") ?? "all";
    for (const profile of catalog.profiles) {
      if (visibility !== "all" && profile.visibility !== visibility) continue;
      console.log(`${profile.name}\t${profile.visibility}\t${profile.summary}`);
    }
    return;
  }

  if (command === "render" && subcommand === "ccr") {
    const profile = requireFlag(rest, "--profile");
    await emitJson(buildCcrConfig(catalog, profile), readFlag(rest, "--out"));
    return;
  }

  if (command === "render" && subcommand === "shell") {
    const profile = requireFlag(rest, "--profile");
    await emitText(buildShellSnippet(catalog, profile), readFlag(rest, "--out"));
    return;
  }

  if (command === "doctor") {
    console.log(`profiles: ${catalog.profiles.length}`);
    console.log("catalog: ok");
    return;
  }

  if (command === "export-oss") {
    await exportOssRelease({ outDir: requireFlag([subcommand, ...rest], "--out") });
    return;
  }

  throw new Error(`unknown command: ${argv.join(" ") || "(none)"}`);
}

async function emitJson(value, outPath) {
  await emitText(`${JSON.stringify(value, null, 2)}\n`, outPath);
}

async function emitText(value, outPath) {
  if (outPath) {
    await mkdir(dirname(outPath), { recursive: true });
    await writeFile(outPath, value);
  } else {
    process.stdout.write(value);
  }
}

function readFlag(args, name) {
  const index = args.indexOf(name);
  return index === -1 ? null : args[index + 1];
}

function requireFlag(args, name) {
  const value = readFlag(args, name);
  if (!value) throw new Error(`missing ${name}`);
  return value;
}

function hasFlag(args, name) {
  return args.includes(name);
}

function defaultConfigDir() {
  return process.env.AIRKIT_CONFIG_DIR ?? join(process.env.XDG_CONFIG_HOME ?? join(homedir(), ".config"), "ai-runtime-kit");
}

function renderInstallPlan(plan) {
  const action = plan.write ? "Wrote" : "Dry run";
  return `${action} airkit profile: ${plan.profile.name}

Files:
- CCR config: ${plan.files.ccrConfig}
- Shell snippet: ${plan.files.shellSnippet}

Next steps:
${plan.nextSteps.map((step) => `- ${step}`).join("\n")}

${plan.write ? "" : "Re-run with --write to create these files.\n"}`;
}

async function writeTextFile(path, content, { force }) {
  if (!force && (await fileExists(path))) {
    throw new Error(`${path} already exists; pass --force to overwrite`);
  }
  await writeFile(path, content);
}

async function fileExists(path) {
  try {
    await access(path);
    return true;
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    throw error;
  }
}

function claudeGuide() {
  const defaultProfile = "openai-compatible-example";

  return `# CLAUDE.md - ai-runtime-kit

## Agent Start Here

This repo is the public OSS for AI runtime profiles. The goal is a guided,
OpenCode-style install flow: inspect first, write only when the user passes
\`--write\`.

Run these from the repo root:

\`\`\`bash
node src/airkit.mjs list
node src/airkit.mjs init --profile ${defaultProfile}
node src/airkit.mjs init --profile ${defaultProfile} --write
node src/airkit.mjs doctor
\`\`\`

The dry run prints every file path it would create. Do not edit runtime files
directly unless the user explicitly asks for a manual repair.

## Product Boundary

- Keep runtime state out of git: Claude sessions, CCR daemon state, caches,
  login state, and secret values.
- Profiles may contain placeholders such as \`$ANTHROPIC_AUTH_TOKEN\`.
- Public output must not contain private endpoints, company names,
  credential-manager item references, or personal/company tokens.

## Release Rules

For public changes:

\`\`\`bash
npm run check
git push
\`\`\`

Do not add private endpoints, company names, credential-manager item references, or
personal/company tokens to this repository.
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(`airkit: ${error.message}`);
    process.exitCode = 1;
  });
}
