#!/usr/bin/env node

import { access, chmod, mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { homedir, tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const defaultCatalogPath = join(repoRoot, "profiles", "catalog.json");

export async function loadCatalog(path = defaultCatalogPath) {
  const raw = await readFile(path, "utf8");
  const catalog = JSON.parse(raw);
  validateCatalog(catalog);
  return catalog;
}

export function buildCcrConfig(catalog, profileName) {
  const profile = findProfile(catalog, profileName);
  if (!profile.ccr) {
    throw new Error(`profile "${profileName}" does not define a CCR config`);
  }
  return structuredClone(profile.ccr);
}

export function buildShellSnippet(catalog, profileName, options = {}) {
  const profile = findProfile(catalog, profileName);
  const shell = profile.shell ?? {};
  const ccrConfigPath = resolve(
    options.ccrConfigPath ?? join(resolve(options.configDir ?? defaultConfigDir()), "ccr", `${profile.name}.json`),
  );
  const ccrConfigEnv = airkitEnvVar("AIRKIT_CCR_CONFIG", profile.name);
  const syncFunction = profile.ccr ? `airkit-sync-ccr-config-${profile.name}` : null;
  const lines = [
    `# Generated by airkit for profile: ${profile.name}`,
    `# ${profile.summary}`,
  ];

  if (profile.ccr) {
    lines.push(`export ${ccrConfigEnv}=${quoteShell(ccrConfigPath)}`);
  }

  if (shell.ccrTokenOpRef) {
    lines.push(`export CCR_ANTHROPIC_AUTH_TOKEN_OP_REF=${quoteShell(shell.ccrTokenOpRef)}`);
  }

  if (syncFunction) {
    lines.push(
      `${syncFunction}() {`,
      `  local _src="\${${ccrConfigEnv}:-}"`,
      `  [[ -n "$_src" ]] || _src=${quoteShell(ccrConfigPath)}`,
      '  local _dst="${AIRKIT_CCR_LIVE_CONFIG:-}"',
      '  [[ -n "$_dst" ]] || _dst="$HOME/.claude-code-router/config.json"',
      '  [[ -r "$_src" ]] || { echo "missing airkit CCR config: $_src" >&2; return 1; }',
      '  command mkdir -p "${_dst:h}" || return',
      '  command cp "$_src" "$_dst"',
      "}",
    );
  }

  if (shell.ccrStartFunction) {
    lines.push(
      `${shell.ccrStartFunction}() {`,
      ...(syncFunction ? [`  ${syncFunction} || return`] : []),
      "  CCR_ANTHROPIC_AUTH_TOKEN_OP_REF=${CCR_ANTHROPIC_AUTH_TOKEN_OP_REF:?missing CCR_ANTHROPIC_AUTH_TOKEN_OP_REF} ccr-start \"$@\"",
      "}",
    );
  }

  for (const wrapper of shell.wrappers ?? []) {
    lines.push(`${wrapper.name}() {`);
    for (const [key, value] of Object.entries(wrapper.env ?? {})) {
      lines.push(`  export ${key}=${quoteShell(value)}`);
    }
    if (syncFunction) {
      lines.push(`  ${syncFunction} || return`);
    }
    lines.push(`  ${wrapper.command} "$@"`, "}");
  }

  return `${lines.join("\n")}\n`;
}

export async function exportOssRelease({ outDir }) {
  if (!outDir) throw new Error("exportOssRelease requires outDir");

  const catalog = await loadCatalog();
  const publicCatalog = {
    schema: catalog.schema,
    ...(catalog.modelCatalog ? { modelCatalog: catalog.modelCatalog } : {}),
    profiles: catalog.profiles.filter((profile) => profile.visibility === "public"),
  };

  await mkdir(join(outDir, "src"), { recursive: true });
  await mkdir(join(outDir, "profiles"), { recursive: true });
  const binPath = join(outDir, "src", "airkit.mjs");
  await writeFile(binPath, await readFile(fileURLToPath(import.meta.url), "utf8"));
  await chmod(binPath, 0o755);
  await writeFile(join(outDir, "profiles", "catalog.json"), `${JSON.stringify(publicCatalog, null, 2)}\n`);
  await writeFile(join(outDir, "package.json"), `${JSON.stringify(publicPackage(), null, 2)}\n`);
  await writeFile(join(outDir, "CLAUDE.md"), claudeGuide());
  await writeFile(join(outDir, "README.md"), publicReadme());
}

export function planInstall(catalog, profileName, options = {}) {
  const profile = findProfile(catalog, profileName);
  const configDir = resolve(options.configDir ?? defaultConfigDir());
  const ccrConfig = join(configDir, "ccr", `${profile.name}.json`);
  const shellSnippet = join(configDir, "shell", `${profile.name}.zsh`);

  return {
    profile: { name: profile.name, summary: profile.summary, visibility: profile.visibility },
    write: options.write === true,
    force: options.force === true,
    files: { ccrConfig, shellSnippet },
    nextSteps: [
      `source ${shellSnippet}`,
      `ccr config: ${ccrConfig}`,
      "Run ccr-start, then launch the rendered wrapper from the shell snippet.",
    ],
  };
}

export async function installProfile(catalog, profileName, options = {}) {
  const plan = planInstall(catalog, profileName, options);
  if (!plan.write) return plan;

  await mkdir(dirname(plan.files.ccrConfig), { recursive: true });
  await mkdir(dirname(plan.files.shellSnippet), { recursive: true });
  const rendered = renderProfile(catalog, profileName, { ccrConfigPath: plan.files.ccrConfig });
  await writeTextFile(plan.files.ccrConfig, rendered.ccrConfig, { force: plan.force });
  await writeTextFile(plan.files.shellSnippet, rendered.shellSnippet, { force: plan.force });
  return plan;
}

export async function updateProfile(catalog, profileName, options = {}) {
  const plan = planInstall(catalog, profileName, options);
  const rendered = renderProfile(catalog, profileName, { ccrConfigPath: plan.files.ccrConfig });
  const previewDir = options.previewDir
    ? resolve(options.previewDir)
    : await mkdtemp(join(tmpdir(), `airkit-${profileName}-update-`));
  const preview = {
    ccrConfig: join(previewDir, "ccr", `${plan.profile.name}.json`),
    shellSnippet: join(previewDir, "shell", `${plan.profile.name}.zsh`),
  };

  await mkdir(dirname(preview.ccrConfig), { recursive: true });
  await mkdir(dirname(preview.shellSnippet), { recursive: true });
  await writeFile(preview.ccrConfig, rendered.ccrConfig);
  await writeFile(preview.shellSnippet, rendered.shellSnippet);

  const files = {
    ccrConfig: await planUpdateFile(plan.files.ccrConfig, preview.ccrConfig, rendered.ccrConfig, "CCR config"),
    shellSnippet: await planUpdateFile(
      plan.files.shellSnippet,
      preview.shellSnippet,
      rendered.shellSnippet,
      "shell snippet",
    ),
  };

  if (plan.write) {
    await mkdir(dirname(plan.files.ccrConfig), { recursive: true });
    await mkdir(dirname(plan.files.shellSnippet), { recursive: true });
    await writeFile(plan.files.ccrConfig, rendered.ccrConfig);
    await writeFile(plan.files.shellSnippet, rendered.shellSnippet);
  }

  return { profile: plan.profile, write: plan.write, previewDir, files };
}

export async function doctorProfile(catalog, profileName, options = {}) {
  const profile = findProfile(catalog, profileName);
  const plan = planInstall(catalog, profileName, options);
  const expected = renderProfile(catalog, profileName, { ccrConfigPath: plan.files.ccrConfig });
  const files = {
    ccrConfig: await checkRenderedFile(plan.files.ccrConfig, expected.ccrConfig, "CCR config"),
    shellSnippet: await checkRenderedFile(plan.files.shellSnippet, expected.shellSnippet, "shell snippet"),
  };
  const runtime = {
    ccr: await checkCcrAvailability(profile, options.commandExists ?? commandExistsOnPath),
    shellSource: files.shellSnippet.ok
      ? await checkShellSourceability(plan.files.shellSnippet, profile, options.sourceShellSnippet ?? sourceShellSnippet)
      : { ok: true, skipped: true, path: plan.files.shellSnippet },
  };
  const failures = Object.values({ ...files, ...runtime })
    .filter((file) => !file.ok)
    .map((file) => file.reason);

  return { ok: failures.length === 0, profile: plan.profile, files, runtime, failures };
}

function findProfile(catalog, profileName) {
  const profile = catalog.profiles.find((candidate) => candidate.name === profileName);
  if (!profile) {
    throw new Error(`unknown profile "${profileName}"`);
  }
  return profile;
}

function validateCatalog(catalog) {
  if (catalog.schema !== 1) throw new Error("catalog schema must be 1");
  if (!Array.isArray(catalog.profiles)) throw new Error("catalog profiles must be an array");

  const seen = new Set();
  for (const profile of catalog.profiles) {
    if (!profile.name || seen.has(profile.name)) throw new Error(`invalid or duplicate profile: ${profile.name}`);
    seen.add(profile.name);
    if (!["internal", "public"].includes(profile.visibility)) {
      throw new Error(`profile "${profile.name}" has invalid visibility`);
    }
    if (profile.ccr) validateCcr(profile.name, profile.ccr);
  }
}

function validateCcr(profileName, ccr) {
  for (const provider of ccr.Providers ?? []) {
    if (typeof provider.api_key === "string" && provider.api_key.startsWith("sk-")) {
      throw new Error(`profile "${profileName}" embeds a secret-looking API key`);
    }
  }
}

function quoteShell(value) {
  return `'${String(value).replaceAll("'", "'\\''")}'`;
}

function airkitEnvVar(prefix, profileName) {
  return `${prefix}_${profileName.toUpperCase().replaceAll(/[^A-Z0-9]+/g, "_")}`;
}

function publicPackage() {
  return {
    name: "@lzong/ai-runtime-kit",
    version: "0.1.0",
    description: "Public-safe runtime profile templates for AI client wrappers.",
    type: "module",
    exports: "./src/airkit.mjs",
    bin: { airkit: "src/airkit.mjs" },
    scripts: { check: "node --check src/airkit.mjs", test: "node --test" },
    engines: { node: ">=20" },
    license: "MIT",
    author: "LZong, Lim, Un-tiong <lzong.tw@gmail.com>",
  };
}

function publicReadme() {
  return `# ai-runtime-kit

Public-safe runtime profile templates for Claude Code Router and other AI client wrappers.

This repository intentionally contains no private endpoints, no credential-manager item references, and no secret values. Use \`profiles/catalog.json\` as a starting point, then keep machine-specific runtime state outside git.

\`\`\`bash
airkit list
airkit init --profile openai-compatible-example
airkit init --profile openai-compatible-example --write
airkit render ccr --profile openai-compatible-example
airkit render shell --profile openai-compatible-example
airkit update --profile openai-compatible-example
airkit doctor --profile openai-compatible-example
\`\`\`

For LLM-guided installation, start with \`CLAUDE.md\`. The normal flow is a dry
run first, then \`--write\` after the user confirms the target paths.
`;
}

export async function runCli(argv = process.argv.slice(2), options = {}) {
  const stdout = options.stdout ?? process.stdout;
  const [command, subcommand, ...rest] = argv;
  const catalog = command === "export-oss" ? null : await loadCatalog(options.catalogPath ?? defaultCatalogPath);

  if (command === "init") {
    const profile = requireFlag([subcommand, ...rest], "--profile");
    const plan = await installProfile(catalog, profile, {
      configDir: readFlag(rest, "--config-dir") ?? defaultConfigDir(),
      force: hasFlag(rest, "--force"),
      write: hasFlag(rest, "--write"),
    });
    stdout.write(renderInstallPlan(plan));
    return 0;
  }

  if (command === "list") {
    const visibility = readFlag(rest, "--visibility") ?? "all";
    for (const profile of catalog.profiles) {
      if (visibility !== "all" && profile.visibility !== visibility) continue;
      stdout.write(`${profile.name}\t${profile.visibility}\t${profile.summary}\n`);
    }
    return 0;
  }

  if (command === "render" && subcommand === "ccr") {
    const profile = requireFlag(rest, "--profile");
    await emitJson(buildCcrConfig(catalog, profile), readFlag(rest, "--out"), stdout);
    return 0;
  }

  if (command === "render" && subcommand === "shell") {
    const profile = requireFlag(rest, "--profile");
    await emitText(buildShellSnippet(catalog, profile), readFlag(rest, "--out"), stdout);
    return 0;
  }

  if (command === "doctor") {
    const args = subcommand ? [subcommand, ...rest] : rest;
    const profile = readFlag(args, "--profile");
    if (!profile) {
      stdout.write(`profiles: ${catalog.profiles.length}\n`);
      stdout.write("catalog: ok\n");
      return 0;
    }

    const result = await doctorProfile(catalog, profile, {
      configDir: readFlag(args, "--config-dir") ?? defaultConfigDir(),
    });
    stdout.write(renderDoctorResult(result));
    return result.ok ? 0 : 1;
  }

  if (command === "update") {
    const args = subcommand ? [subcommand, ...rest] : rest;
    const profile = requireFlag(args, "--profile");
    const result = await updateProfile(catalog, profile, {
      configDir: readFlag(args, "--config-dir") ?? defaultConfigDir(),
      previewDir: readFlag(args, "--preview-dir"),
      write: hasFlag(args, "--write"),
    });
    stdout.write(renderUpdateResult(result));
    return 0;
  }

  if (command === "export-oss") {
    await exportOssRelease({ outDir: requireFlag([subcommand, ...rest], "--out") });
    return 0;
  }

  throw new Error(`unknown command: ${argv.join(" ") || "(none)"}`);
}

async function emitJson(value, outPath, stdout = process.stdout) {
  await emitText(`${JSON.stringify(value, null, 2)}\n`, outPath, stdout);
}

async function emitText(value, outPath, stdout = process.stdout) {
  if (outPath) {
    await mkdir(dirname(outPath), { recursive: true });
    await writeFile(outPath, value);
  } else {
    stdout.write(value);
  }
}

function readFlag(args, name) {
  const index = args.indexOf(name);
  return index === -1 ? null : args[index + 1];
}

function requireFlag(args, name) {
  const value = readFlag(args, name);
  if (!value) throw new Error(`missing ${name}`);
  return value;
}

function hasFlag(args, name) {
  return args.includes(name);
}

function defaultConfigDir() {
  return process.env.AIRKIT_CONFIG_DIR ?? join(process.env.XDG_CONFIG_HOME ?? join(homedir(), ".config"), "ai-runtime-kit");
}

function renderInstallPlan(plan) {
  const action = plan.write ? "Wrote" : "Dry run";
  return `${action} airkit profile: ${plan.profile.name}

Files:
- CCR config: ${plan.files.ccrConfig}
- Shell snippet: ${plan.files.shellSnippet}

Next steps:
${plan.nextSteps.map((step) => `- ${step}`).join("\n")}

${plan.write ? "" : "Re-run with --write to create these files.\n"}`;
}

function renderUpdateResult(result) {
  const action = result.write ? "Wrote" : "Dry run";
  return `${action} update airkit profile: ${result.profile.name}

Targets:
- ${result.files.ccrConfig.status} CCR config: ${result.files.ccrConfig.target}
- ${result.files.shellSnippet.status} shell snippet: ${result.files.shellSnippet.target}

Preview files:
- CCR config: ${result.files.ccrConfig.preview}
- Shell snippet: ${result.files.shellSnippet.preview}

Diff summary:
- CCR config: ${result.files.ccrConfig.diff}
- Shell snippet: ${result.files.shellSnippet.diff}

${result.write ? "" : "Re-run with --write to overwrite stale or missing target files.\n"}`;
}

function renderProfile(catalog, profileName, options = {}) {
  return {
    ccrConfig: `${JSON.stringify(buildCcrConfig(catalog, profileName), null, 2)}\n`,
    shellSnippet: buildShellSnippet(catalog, profileName, options),
  };
}

async function writeTextFile(path, content, { force }) {
  if (!force && (await fileExists(path))) {
    throw new Error(`${path} already exists; pass --force to overwrite`);
  }
  await writeFile(path, content);
}

async function checkRenderedFile(path, expected, label) {
  let actual;
  try {
    actual = await readFile(path, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") {
      return { ok: false, path, reason: `missing ${label}: ${path}` };
    }
    throw error;
  }

  if (actual !== expected) {
    return { ok: false, path, reason: `stale ${label}: ${path}` };
  }
  return { ok: true, path };
}

async function planUpdateFile(target, preview, expected, label) {
  let actual;
  try {
    actual = await readFile(target, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") {
      return { status: "missing", target, preview, diff: `missing ${label}; would create` };
    }
    throw error;
  }

  if (actual === expected) {
    return { status: "current", target, preview, diff: "no changes" };
  }

  return { status: "stale", target, preview, diff: describeTextDiff(actual, expected) };
}

function describeTextDiff(actual, expected) {
  const actualLines = actual.split("\n");
  const expectedLines = expected.split("\n");
  const lineCount = Math.max(actualLines.length, expectedLines.length);

  for (let index = 0; index < lineCount; index += 1) {
    if (actualLines[index] !== expectedLines[index]) {
      return `first difference at line ${index + 1}`;
    }
  }

  return "content differs";
}

function renderDoctorResult(result) {
  const lines = [
    `profile: ${result.profile.name}`,
    `${result.files.ccrConfig.ok ? "ok" : "fail"} CCR config: ${result.files.ccrConfig.path}`,
    `${result.files.shellSnippet.ok ? "ok" : "fail"} shell snippet: ${result.files.shellSnippet.path}`,
    `${statusOf(result.runtime.ccr)} CCR availability: ${result.runtime.ccr.command}`,
    `${statusOf(result.runtime.shellSource)} shell source: ${result.runtime.shellSource.path}`,
  ];
  for (const failure of result.failures) {
    lines.push(`- ${failure}`);
  }
  return `${lines.join("\n")}\n`;
}

async function checkCcrAvailability(profile, commandExists) {
  if (!profile.ccr) {
    return { ok: true, skipped: true, command: "ccr" };
  }
  if (await commandExists("ccr")) {
    return { ok: true, command: "ccr" };
  }
  return { ok: false, command: "ccr", reason: "missing command: ccr" };
}

async function checkShellSourceability(path, profile, sourceSnippet) {
  const result = await sourceSnippet(path, shellFunctionNames(profile));
  if (result.ok) {
    return { ok: true, path };
  }

  const detail = result.detail ? ` (${result.detail})` : "";
  return { ok: false, path, reason: `shell snippet is not sourceable: ${path}${detail}` };
}

function commandExistsOnPath(command) {
  const result = spawnSync("sh", ["-c", 'command -v "$1" >/dev/null 2>&1', "airkit-command-check", command], {
    stdio: "ignore",
  });
  return result.status === 0;
}

function sourceShellSnippet(path, functionNames) {
  const script = 'source "$1" || exit $?; shift; for fn in "$@"; do typeset -f "$fn" >/dev/null || exit 1; done';
  const result = spawnSync("zsh", ["-fc", script, "airkit-source-check", path, ...functionNames], {
    encoding: "utf8",
  });
  if (result.error) {
    return { ok: false, detail: result.error.message };
  }
  if (result.status === 0) {
    return { ok: true };
  }

  const detail = [result.stderr?.trim(), result.stdout?.trim()].filter(Boolean).join("; ");
  return { ok: false, detail: detail || `zsh exited ${result.status}` };
}

function shellFunctionNames(profile) {
  const shell = profile.shell ?? {};
  return [shell.ccrStartFunction, ...(shell.wrappers ?? []).map((wrapper) => wrapper.name)].filter(Boolean);
}

function statusOf(check) {
  if (check.skipped) return "skip";
  return check.ok ? "ok" : "fail";
}

async function fileExists(path) {
  try {
    await access(path);
    return true;
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    throw error;
  }
}

function claudeGuide() {
  const defaultProfile = "openai-compatible-example";

  return `# CLAUDE.md - ai-runtime-kit

## Agent Start Here

This repo is the public OSS for AI runtime profiles. The goal is a guided,
OpenCode-style install flow: inspect first, write only when the user passes
\`--write\`.

Run these from the repo root:

\`\`\`bash
node src/airkit.mjs list
node src/airkit.mjs init --profile ${defaultProfile}
node src/airkit.mjs init --profile ${defaultProfile} --write
node src/airkit.mjs doctor
\`\`\`

The dry run prints every file path it would create. Do not edit runtime files
directly unless the user explicitly asks for a manual repair.

## Product Boundary

- Keep runtime state out of git: Claude sessions, CCR daemon state, caches,
  login state, and secret values.
- Profiles may contain placeholders such as \`$ANTHROPIC_AUTH_TOKEN\`.
- Public output must not contain private endpoints, company names,
  credential-manager item references, or personal/company tokens.

## Release Rules

For public changes:

\`\`\`bash
npm run check
git push
\`\`\`

Do not add private endpoints, company names, credential-manager item references, or
personal/company tokens to this repository.
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runCli()
    .then((exitCode) => {
      process.exitCode = exitCode;
    })
    .catch((error) => {
      console.error(`airkit: ${error.message}`);
      process.exitCode = 1;
    });
}
