#!/usr/bin/env node

import { access, chmod, copyFile, mkdir, mkdtemp, readdir, readFile, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, realpathSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { basename, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const defaultCatalogPath = join(repoRoot, "profiles", "catalog.json");
const reusableRuntimeLessonsPrompt = [
  "AirKit reusable runtime lessons:",
  "Treat durable lessons, project memory, and user corrections as hard constraints. Before retrying a failed command, check whether the failure matches a known lesson.",
  "When a user correction or repeated tool failure reveals a durable lesson, record it in the workspace's durable notes when available, using Symptom/Cause/Rule/Action/Verify. Do not record secrets, private endpoints, credential values, or company-only identifiers in shared notes.",
  "For Athena and similar query services, never assume the database, catalog, region, workgroup, or result output location. Discover or verify them first, pass explicit query context and result configuration, and inspect get-query-execution StateChangeReason before calling get-query-results after a failure.",
  "When a command fails inside a shell wrapper, first verify whether the command is a shell wrapper or the real binary with type, command -v, or whence. Rule out local shell wrapper/helper leakage before diagnosing the remote service.",
].join(" ");

export async function loadCatalog(path = defaultCatalogPath) {
  const raw = await readFile(path, "utf8");
  const catalog = JSON.parse(raw);
  validateCatalog(catalog);
  return catalog;
}

export function buildCcrConfig(catalog, profileName, options = {}) {
  const profile = findProfile(catalog, profileName);
  if (!profile.ccr) {
    throw new Error(`profile "${profileName}" does not define a CCR config`);
  }
  return renderTemplateValue(structuredClone(profile.ccr), profileTemplateVars(profile, options.configDir));
}

export function buildShellSnippet(catalog, profileName, options = {}) {
  const profile = findProfile(catalog, profileName);
  const shell = profile.shell ?? {};
  const templateVars = profileTemplateVars(profile, options.configDir);
  const ccrConfigPath = resolve(
    options.ccrConfigPath ?? join(resolve(options.configDir ?? defaultConfigDir()), "ccr", `${profile.name}.json`),
  );
  const ccrConfigEnv = airkitEnvVar("AIRKIT_CCR_CONFIG", profile.name);
  const snippetConfigDir = resolve(options.configDir ?? defaultConfigDir());
  const transformerDir = join(snippetConfigDir, "ccr", "transformers");
  const ccrLoadMarker = join(snippetConfigDir, "cache", `ccr-loaded.${profile.name}.sig`);
  const syncFunction = profile.ccr ? `airkit-sync-ccr-config-${profile.name}` : null;
  const lines = [
    `# Generated by airkit for profile: ${profile.name}`,
    `# ${profile.summary}`,
  ];

  if (profile.ccr) {
    lines.push(`export ${ccrConfigEnv}=${quoteShell(ccrConfigPath)}`);
  }

  if (shell.ccrTokenOpRef) {
    lines.push(`export CCR_ANTHROPIC_AUTH_TOKEN_OP_REF=${quoteShell(shell.ccrTokenOpRef)}`);
  }

  if (syncFunction) {
    lines.push(
      `${syncFunction}() {`,
      `  local _src="\${${ccrConfigEnv}:-}"`,
      `  [[ -n "$_src" ]] || _src=${quoteShell(ccrConfigPath)}`,
      '  local _dst="${AIRKIT_CCR_LIVE_CONFIG:-}"',
      '  [[ -n "$_dst" ]] || _dst="$HOME/.claude-code-router/config.json"',
      '  [[ -r "$_src" ]] || { echo "missing airkit CCR config: $_src" >&2; return 1; }',
      '  command mkdir -p "${_dst:h}" || return',
      '  command cp "$_src" "$_dst"',
      "}",
    );
  }

  // `ccr start` never reloads an already-running daemon (it is a no-op), so a changed transformer
  // or config would be silently ignored until a manual restart. This helper hashes the live config
  // plus the bundled transformer files against a marker and stops CCR only when they changed, so the
  // next start reloads. Both the start function and the launch wrapper call it (the wrapper delegates
  // to a shell `cclaude` that only starts CCR when down, never restarts — so the check must run here).
  const reloadFunction = profile.ccr ? `airkit-ccr-reload-if-changed-${profile.name}` : null;
  if (reloadFunction) {
    lines.push(
      `${reloadFunction}() {`,
      '  local _airkit_live="${AIRKIT_CCR_LIVE_CONFIG:-$HOME/.claude-code-router/config.json}"',
      `  local _airkit_tdir=${quoteShell(transformerDir)}`,
      `  local _airkit_marker=${quoteShell(ccrLoadMarker)}`,
      "  local _airkit_sig",
      '  _airkit_sig="$(command cat "$_airkit_live" "$_airkit_tdir"/*(.N) 2>/dev/null | command shasum 2>/dev/null | command awk \'{ print $1 }\')"',
      '  [[ -n "$_airkit_sig" ]] || return 0',
      '  if [[ "$_airkit_sig" != "$(command cat "$_airkit_marker" 2>/dev/null)" ]]; then',
      "    command ccr stop > /dev/null 2>&1",
      '    command mkdir -p "${_airkit_marker:h}" && print -r -- "$_airkit_sig" > "$_airkit_marker"',
      "  fi",
      "}",
    );
  }

  if (shell.ccrStartFunction) {
    lines.push(
      `${shell.ccrStartFunction}() {`,
      ...(syncFunction ? [`  ${syncFunction} || return`] : []),
      ...(reloadFunction ? [`  ${reloadFunction}`] : []),
      "  CCR_ANTHROPIC_AUTH_TOKEN_OP_REF=${CCR_ANTHROPIC_AUTH_TOKEN_OP_REF:?missing CCR_ANTHROPIC_AUTH_TOKEN_OP_REF} ccr-start \"$@\"",
      "}",
    );
  }

  for (const wrapper of shell.wrappers ?? []) {
    lines.push(`${wrapper.name}() {`);
    for (const [key, value] of Object.entries(wrapper.env ?? {})) {
      lines.push(`  export ${key}=${quoteShell(renderTemplateValue(value, templateVars))}`);
    }
    if (syncFunction) {
      lines.push(`  ${syncFunction} || return`);
    }
    if (reloadFunction) {
      lines.push(`  ${reloadFunction}`);
    }
    const rawWrapperArgs = (wrapper.args ?? []).map((arg) => renderTemplateValue(arg, templateVars));
    const wrapperCcrConfig = profile.ccr ? buildCcrConfig(catalog, profileName, { configDir: options.configDir }) : null;
    const effectiveWrapperArgs = shouldAppendReusableRuntimeLessons(wrapper.command)
      ? appendRuntimePrompts(rawWrapperArgs, [
          reusableRuntimeLessonsPrompt,
          wrapperCcrConfig
            ? airclaudeRoutingPrompt(wrapper.env?.AIRCLAUDE_MODE ?? "auto", wrapperCcrConfig, resolveRestoreRepairConfig(profile))
            : "",
        ])
      : rawWrapperArgs;
    const wrapperArgs = effectiveWrapperArgs.map((arg) => quoteShell(arg));
    const renderedArgs = wrapperArgs.length ? ` ${wrapperArgs.join(" ")}` : "";
    lines.push(`  ${wrapper.command}${renderedArgs} "$@"`, "}");
  }

  return `${lines.join("\n")}\n`;
}

export async function exportOssRelease({ outDir }) {
  if (!outDir) throw new Error("exportOssRelease requires outDir");

  const catalog = await loadCatalog();
  const publicCatalog = {
    schema: catalog.schema,
    ...(catalog.modelCatalog ? { modelCatalog: catalog.modelCatalog } : {}),
    profiles: catalog.profiles.filter((profile) => profile.visibility === "public"),
  };

  await mkdir(join(outDir, "src"), { recursive: true });
  await mkdir(join(outDir, "profiles"), { recursive: true });
  const binPath = join(outDir, "src", "airkit.mjs");
  await writeFile(binPath, await readFile(fileURLToPath(import.meta.url), "utf8"));
  await chmod(binPath, 0o755);
  await writeFile(join(outDir, "profiles", "catalog.json"), `${JSON.stringify(publicCatalog, null, 2)}\n`);
  await writeFile(join(outDir, "package.json"), `${JSON.stringify(publicPackage(), null, 2)}\n`);
  await writeFile(join(outDir, "CLAUDE.md"), claudeGuide());
  await writeFile(join(outDir, "README.md"), publicReadme());
}

export function planInstall(catalog, profileName, options = {}) {
  const profile = findProfile(catalog, profileName);
  const configDir = resolve(options.configDir ?? defaultConfigDir());
  const ccrConfig = join(configDir, "ccr", `${profile.name}.json`);
  const shellSnippet = join(configDir, "shell", `${profile.name}.zsh`);
  const managedFiles = renderManagedFiles(profile, { configDir }).map((file) => ({
    label: file.label,
    path: file.path,
  }));

  return {
    profile: { name: profile.name, summary: profile.summary, visibility: profile.visibility },
    configDir,
    write: options.write === true,
    force: options.force === true,
    files: { ccrConfig, shellSnippet, managedFiles },
    nextSteps: [
      `source ${shellSnippet}`,
      `ccr config: ${ccrConfig}`,
      "Run ccr-start, then launch the rendered wrapper from the shell snippet.",
    ],
  };
}

export async function installProfile(catalog, profileName, options = {}) {
  const plan = planInstall(catalog, profileName, options);
  if (!plan.write) return plan;

  await mkdir(dirname(plan.files.ccrConfig), { recursive: true });
  await mkdir(dirname(plan.files.shellSnippet), { recursive: true });
  const rendered = renderProfile(catalog, profileName, { configDir: plan.configDir, ccrConfigPath: plan.files.ccrConfig });
  await writeTextFile(plan.files.ccrConfig, rendered.ccrConfig, { force: plan.force });
  await writeTextFile(plan.files.shellSnippet, rendered.shellSnippet, { force: plan.force });
  for (const file of rendered.managedFiles) {
    await mkdir(dirname(file.path), { recursive: true });
    await writeTextFile(file.path, file.content, { force: plan.force });
  }
  return plan;
}

export async function updateProfile(catalog, profileName, options = {}) {
  const plan = planInstall(catalog, profileName, options);
  const rendered = renderProfile(catalog, profileName, { configDir: plan.configDir, ccrConfigPath: plan.files.ccrConfig });
  const previewDir = options.previewDir
    ? resolve(options.previewDir)
    : await mkdtemp(join(tmpdir(), `airkit-${profileName}-update-`));
  const preview = {
    ccrConfig: join(previewDir, "ccr", `${plan.profile.name}.json`),
    shellSnippet: join(previewDir, "shell", `${plan.profile.name}.zsh`),
    managedFiles: rendered.managedFiles.map((file) => ({
      ...file,
      preview: join(previewDir, file.relativePath),
    })),
  };

  await mkdir(dirname(preview.ccrConfig), { recursive: true });
  await mkdir(dirname(preview.shellSnippet), { recursive: true });
  await writeFile(preview.ccrConfig, rendered.ccrConfig);
  await writeFile(preview.shellSnippet, rendered.shellSnippet);
  for (const file of preview.managedFiles) {
    await mkdir(dirname(file.preview), { recursive: true });
    await writeFile(file.preview, file.content);
  }

  const files = {
    ccrConfig: await planUpdateFile(plan.files.ccrConfig, preview.ccrConfig, rendered.ccrConfig, "CCR config"),
    shellSnippet: await planUpdateFile(
      plan.files.shellSnippet,
      preview.shellSnippet,
      rendered.shellSnippet,
      "shell snippet",
    ),
    managedFiles: await Promise.all(
      preview.managedFiles.map((file) => planUpdateFile(file.path, file.preview, file.content, file.label)),
    ),
  };

  if (plan.write) {
    await mkdir(dirname(plan.files.ccrConfig), { recursive: true });
    await mkdir(dirname(plan.files.shellSnippet), { recursive: true });
    await writeFile(plan.files.ccrConfig, rendered.ccrConfig);
    await writeFile(plan.files.shellSnippet, rendered.shellSnippet);
    for (const file of rendered.managedFiles) {
      await mkdir(dirname(file.path), { recursive: true });
      await writeFile(file.path, file.content);
    }
  }

  return { profile: plan.profile, write: plan.write, previewDir, files };
}

export function buildLaunchPlan(catalog, profileName, options = {}) {
  const profile = findProfile(catalog, profileName);
  const configDir = resolve(options.configDir ?? defaultConfigDir());
  const templateVars = profileTemplateVars(profile, configDir);
  const launch = resolveLaunchConfig(profile, templateVars);
  const mode = resolveLaunchMode(profile, launch, options.mode);
  const ccrConfig = applyLaunchModeOverlay(buildCcrConfig(catalog, profileName, { configDir }), profile, mode, templateVars);
  const restore = resolveRestoreRepairConfig(profile);
  const launchVars = launchTemplateVars(profile, configDir, mode, ccrConfig, restore);
  const basePlan = planInstall(catalog, profileName, { configDir, write: true, force: true });
  const liveCcrConfig = resolve(
    options.liveCcrConfig ?? process.env.AIRKIT_CCR_LIVE_CONFIG ?? join(homedir(), ".claude-code-router", "config.json"),
  );

  return {
    profile: basePlan.profile,
    mode,
    configDir,
    files: basePlan.files,
    ccrConfig,
    liveCcrConfig: { path: liveCcrConfig },
    credential: {
      ccrTokenOpRef: profile.shell?.ccrTokenOpRef ?? null,
    },
    launch: {
      command: renderTemplateValue(launch.binary, launchVars),
      args: appendLaunchRuntimePrompts(
        (launch.args ?? []).map((arg) => renderTemplateValue(arg, launchVars)),
        launch.binary,
        mode,
        ccrConfig,
        restore,
      ),
      env: {
        ...airclaudeLaunchEnv(catalog, profile, mode, ccrConfig, restore),
        ...renderTemplateValue(launch.env ?? {}, launchVars),
      },
      userArgs: options.userArgs ?? [],
    },
  };
}

export async function prepareLaunch(catalog, profileName, options = {}) {
  const plan = buildLaunchPlan(catalog, profileName, options);
  const rendered = renderProfile(catalog, profileName, {
    configDir: plan.configDir,
    ccrConfigPath: plan.files.ccrConfig,
  });
  const files = await planLaunchFiles(plan, rendered);

  if (options.dryRun || options.doctor) {
    return {
      ...plan,
      write: false,
      files,
      liveCcrConfig: { ...plan.liveCcrConfig, status: "would-sync" },
      runtime: await checkLaunchRuntime(plan, options),
    };
  }

  await writeLaunchFiles(plan, rendered);
  await mkdir(dirname(plan.liveCcrConfig.path), { recursive: true });
  await writeFile(plan.liveCcrConfig.path, `${JSON.stringify(plan.ccrConfig, null, 2)}\n`);
  const restoreRepair = await repairClaudeRestoreSessions(catalog, profileName, {
    backupsDir: options.backupsDir,
    projectsDir: options.projectsDir,
    write: true,
  });
  const runtime = await checkLaunchRuntime(plan, options);
  if (!runtime.ccr.ok) throw new Error(runtime.ccr.reason);
  if (!runtime.launch.ok) throw new Error(runtime.launch.reason);
  const launchEnv = { ...(runtime.ccr.env ?? {}), ...plan.launch.env };

  let child = null;
  if (options.launch !== false) {
    const spawnCommand = options.spawnCommand ?? spawnCommandSync;
    child = spawnCommand(plan.launch.command, [...plan.launch.args, ...plan.launch.userArgs], {
      env: launchEnv,
      stdio: "inherit",
    });
  }

  return {
    ...plan,
    write: true,
    files: await planLaunchFiles(plan, rendered),
    liveCcrConfig: { ...plan.liveCcrConfig, status: "synced" },
    runtime,
    restoreRepair,
    child,
  };
}

export async function repairClaudeRestoreSessions(catalog, profileName, options = {}) {
  const profile = findProfile(catalog, profileName);
  const restore = resolveRestoreRepairConfig(profile);
  const projectsDir = resolve(options.projectsDir ?? claudeRestoreProjectsDir());
  const result = {
    profile: { name: profile.name, summary: profile.summary, visibility: profile.visibility },
    enabled: Boolean(restore),
    model: restore?.model ?? null,
    projectsDir,
    backupsDir: null,
    scannedFiles: 0,
    repairedFiles: 0,
    repairedLines: 0,
    backups: [],
    write: options.write !== false,
  };
  if (!restore) return result;

  const files = await listClaudeSessionFiles(projectsDir);
  result.scannedFiles = files.length;

  for (const file of files) {
    const original = await readFile(file, "utf8");
    const repaired = repairClaudeSessionText(original, restore);
    if (repaired.repairedLines === 0) continue;

    result.repairedFiles += 1;
    result.repairedLines += repaired.repairedLines;
    if (!result.write) continue;

    if (!result.backupsDir) {
      result.backupsDir = resolve(
        options.backupsDir ?? join(homedir(), ".claude", "backups", `airkit-restore-${timestampForPath()}`),
      );
      await mkdir(result.backupsDir, { recursive: true });
    }
    const backup = restoreBackupPath(result.backupsDir, projectsDir, file);
    await copyFile(file, backup);
    await writeFile(file, repaired.text);
    result.backups.push(backup);
  }

  return result;
}

export async function doctorProfile(catalog, profileName, options = {}) {
  const profile = findProfile(catalog, profileName);
  const plan = planInstall(catalog, profileName, options);
  const expected = renderProfile(catalog, profileName, { configDir: plan.configDir, ccrConfigPath: plan.files.ccrConfig });
  const files = {
    ccrConfig: await checkRenderedFile(plan.files.ccrConfig, expected.ccrConfig, "CCR config"),
    shellSnippet: await checkRenderedFile(plan.files.shellSnippet, expected.shellSnippet, "shell snippet"),
    managedFiles: await Promise.all(
      expected.managedFiles.map((file) => checkRenderedFile(file.path, file.content, file.label)),
    ),
  };
  const runtime = {
    ccr: await checkCcrAvailability(profile, options.commandExists ?? commandExistsOnPath),
    shellSource: files.shellSnippet.ok
      ? await checkShellSourceability(plan.files.shellSnippet, profile, options.sourceShellSnippet ?? sourceShellSnippet)
      : { ok: true, skipped: true, path: plan.files.shellSnippet },
  };
  const failures = [files.ccrConfig, files.shellSnippet, ...files.managedFiles, ...Object.values(runtime)]
    .filter((file) => !file.ok)
    .map((file) => file.reason);

  return { ok: failures.length === 0, profile: plan.profile, files, runtime, failures };
}

function findProfile(catalog, profileName) {
  const profile = catalog.profiles.find((candidate) => candidate.name === profileName);
  if (!profile) {
    throw new Error(`unknown profile "${profileName}"`);
  }
  return profile;
}

function validateCatalog(catalog) {
  if (catalog.schema !== 1) throw new Error("catalog schema must be 1");
  if (!Array.isArray(catalog.profiles)) throw new Error("catalog profiles must be an array");

  const seen = new Set();
  for (const profile of catalog.profiles) {
    if (!profile.name || seen.has(profile.name)) throw new Error(`invalid or duplicate profile: ${profile.name}`);
    seen.add(profile.name);
    if (!["internal", "public"].includes(profile.visibility)) {
      throw new Error(`profile "${profile.name}" has invalid visibility`);
    }
    if (profile.ccr) validateCcr(profile.name, profile.ccr);
    validateManagedFiles(profile);
  }
}

function validateCcr(profileName, ccr) {
  for (const provider of ccr.Providers ?? []) {
    if (typeof provider.api_key === "string" && provider.api_key.startsWith("sk-")) {
      throw new Error(`profile "${profileName}" embeds a secret-looking API key`);
    }
  }
}

function validateManagedFiles(profile) {
  for (const file of profile.managedFiles ?? []) {
    if (!file.path || typeof file.content !== "string") {
      throw new Error(`profile "${profile.name}" has an invalid managed file`);
    }
    if (file.path.startsWith("/") || file.path.split("/").includes("..")) {
      throw new Error(`profile "${profile.name}" managed file must stay inside the config dir: ${file.path}`);
    }
  }
}

function quoteShell(value) {
  return `'${String(value).replaceAll("'", "'\\''")}'`;
}

function airkitEnvVar(prefix, profileName) {
  return `${prefix}_${profileName.toUpperCase().replaceAll(/[^A-Z0-9]+/g, "_")}`;
}

function publicPackage() {
  return {
    name: "@lzong/ai-runtime-kit",
    version: "0.2.0",
    description: "Public-safe runtime profile templates for AI client wrappers.",
    type: "module",
    exports: "./src/airkit.mjs",
    bin: { airkit: "src/airkit.mjs", airclaude: "src/airkit.mjs" },
    scripts: {
      check: "node --check src/airkit.mjs",
      "pack:check": "npm pack --dry-run",
      test: "node --test",
      verify: "npm test && npm run check && npm run pack:check",
    },
    engines: { node: ">=20" },
    license: "MIT",
    author: "LZong, Lim, Un-tiong <lzong.tw@gmail.com>",
  };
}

function publicReadme() {
  return `# ai-runtime-kit

Public-safe runtime profile templates for Claude Code Router and other AI client wrappers.

This repository intentionally contains no private endpoints, no credential-manager item references, and no secret values. Use \`profiles/catalog.json\` as a starting point, then keep machine-specific runtime state outside git.

\`\`\`bash
airclaude
airclaude pro
airclaude --dry-run
airclaude --doctor
airclaude --help
airkit list
airkit --help
airkit init --profile openai-compatible-example
airkit init --profile openai-compatible-example --write
airkit render ccr --profile openai-compatible-example
airkit render shell --profile openai-compatible-example
airkit update --profile openai-compatible-example
airkit doctor --profile openai-compatible-example
\`\`\`

\`airclaude\` is the daily entrypoint. It automatically renders managed files,
syncs the CCR live config, starts CCR when needed, and launches Claude Code.
\`airclaude pro\` applies the profile's stronger routing overlay before launch.

For LLM-guided installation or debugging, start with \`CLAUDE.md\`. The
management flow remains inspectable: dry run first, then \`--write\` after the
user confirms the target paths.
`;
}

export async function runCli(argv = process.argv.slice(2), options = {}) {
  const stdout = options.stdout ?? process.stdout;
  const [command, subcommand, ...rest] = argv;

  if (isHelpRequest(argv)) {
    stdout.write(renderAirkitHelp());
    return 0;
  }

  if (command === "airclaude") {
    return runAirclaudeCli([subcommand, ...rest].filter((arg) => arg !== undefined), options);
  }

  const catalog = command === "export-oss" ? null : await loadCatalog(options.catalogPath ?? defaultCatalogPath);

  if (command === "init") {
    const profile = requireFlag([subcommand, ...rest], "--profile");
    const plan = await installProfile(catalog, profile, {
      configDir: readFlag(rest, "--config-dir") ?? defaultConfigDir(),
      force: hasFlag(rest, "--force"),
      write: hasFlag(rest, "--write"),
    });
    stdout.write(renderInstallPlan(plan));
    return 0;
  }

  if (command === "list") {
    const visibility = readFlag(rest, "--visibility") ?? "all";
    for (const profile of catalog.profiles) {
      if (visibility !== "all" && profile.visibility !== visibility) continue;
      stdout.write(`${profile.name}\t${profile.visibility}\t${profile.summary}\n`);
    }
    return 0;
  }

  if (command === "render" && subcommand === "ccr") {
    const profile = requireFlag(rest, "--profile");
    await emitJson(buildCcrConfig(catalog, profile), readFlag(rest, "--out"), stdout);
    return 0;
  }

  if (command === "render" && subcommand === "shell") {
    const profile = requireFlag(rest, "--profile");
    await emitText(buildShellSnippet(catalog, profile), readFlag(rest, "--out"), stdout);
    return 0;
  }

  if (command === "doctor") {
    const args = subcommand ? [subcommand, ...rest] : rest;
    const profile = readFlag(args, "--profile");
    if (!profile) {
      stdout.write(`profiles: ${catalog.profiles.length}\n`);
      stdout.write("catalog: ok\n");
      return 0;
    }

    const result = await doctorProfile(catalog, profile, {
      configDir: readFlag(args, "--config-dir") ?? defaultConfigDir(),
    });
    stdout.write(renderDoctorResult(result));
    return result.ok ? 0 : 1;
  }

  if (command === "update") {
    const args = subcommand ? [subcommand, ...rest] : rest;
    const profile = requireFlag(args, "--profile");
    const result = await updateProfile(catalog, profile, {
      configDir: readFlag(args, "--config-dir") ?? defaultConfigDir(),
      previewDir: readFlag(args, "--preview-dir"),
      write: hasFlag(args, "--write"),
    });
    stdout.write(renderUpdateResult(result));
    return 0;
  }

  if (command === "export-oss") {
    await exportOssRelease({ outDir: requireFlag([subcommand, ...rest], "--out") });
    return 0;
  }

  throw new Error(`unknown command: ${argv.join(" ") || "(none)"}`);
}

export async function runAirclaudeCli(argv = process.argv.slice(2), options = {}) {
  const stdout = options.stdout ?? process.stdout;

  if (isHelpRequest(argv)) {
    stdout.write(renderAirclaudeHelp());
    return 0;
  }

  const catalog = await loadCatalog(options.catalogPath ?? defaultCatalogPath);
  const parsed = parseAirclaudeArgs(argv);
  const profile = parsed.profile ?? process.env.AIRCLAUDE_PROFILE ?? defaultLaunchProfile(catalog);
  if (parsed.repairRestore) {
    const result = await repairClaudeRestoreSessions(catalog, profile, {
      backupsDir: parsed.backupsDir ?? options.backupsDir,
      projectsDir: parsed.projectsDir ?? options.projectsDir,
      write: true,
    });
    stdout.write(renderRestoreRepairResult(result));
    return 0;
  }

  const result = await prepareLaunch(catalog, profile, {
    ...options,
    configDir: parsed.configDir ?? options.configDir ?? defaultConfigDir(),
    doctor: parsed.doctor,
    dryRun: parsed.dryRun || parsed.doctor,
    launch: !parsed.dryRun && !parsed.doctor,
    mode: parsed.mode,
    backupsDir: parsed.backupsDir ?? options.backupsDir,
    projectsDir: parsed.projectsDir ?? options.projectsDir,
    userArgs: parsed.userArgs,
  });
  stdout.write(renderLaunchResult(result, { doctor: parsed.doctor, dryRun: parsed.dryRun }));
  return result.child?.status ?? 0;
}

function isHelpRequest(argv) {
  const [first] = argv;
  return first === "-h" || first === "--help" || first === "help";
}

async function emitJson(value, outPath, stdout = process.stdout) {
  await emitText(`${JSON.stringify(value, null, 2)}\n`, outPath, stdout);
}

async function emitText(value, outPath, stdout = process.stdout) {
  if (outPath) {
    await mkdir(dirname(outPath), { recursive: true });
    await writeFile(outPath, value);
  } else {
    stdout.write(value);
  }
}

function parseAirclaudeArgs(argv) {
  const parsed = { userArgs: [] };
  const passthroughIndex = argv.indexOf("--");
  const ownArgs = passthroughIndex === -1 ? argv : argv.slice(0, passthroughIndex);
  parsed.userArgs.push(...(passthroughIndex === -1 ? [] : argv.slice(passthroughIndex + 1)));

  for (let index = 0; index < ownArgs.length; index += 1) {
    const arg = ownArgs[index];
    if (arg === "--profile") {
      parsed.profile = ownArgs[++index];
    } else if (arg === "--config-dir") {
      parsed.configDir = ownArgs[++index];
    } else if (arg === "--mode") {
      parsed.mode = ownArgs[++index];
    } else if (arg === "--dry-run") {
      parsed.dryRun = true;
    } else if (arg === "--doctor") {
      parsed.doctor = true;
    } else if (arg === "--repair-restore") {
      parsed.repairRestore = true;
    } else if (arg === "--restore-projects-dir") {
      parsed.projectsDir = ownArgs[++index];
    } else if (arg === "--restore-backups-dir") {
      parsed.backupsDir = ownArgs[++index];
    } else if ((arg === "auto" || arg === "pro") && !parsed.mode) {
      parsed.mode = arg;
    } else {
      parsed.userArgs.push(arg);
    }
  }

  return parsed;
}

function defaultLaunchProfile(catalog) {
  const profile = catalog.profiles.find((candidate) => candidate.launch || candidate.ccr);
  if (!profile) throw new Error("catalog does not define a launchable profile");
  return profile.name;
}

function readFlag(args, name) {
  const index = args.indexOf(name);
  return index === -1 ? null : args[index + 1];
}

function requireFlag(args, name) {
  const value = readFlag(args, name);
  if (!value) throw new Error(`missing ${name}`);
  return value;
}

function hasFlag(args, name) {
  return args.includes(name);
}

function defaultConfigDir() {
  return process.env.AIRKIT_CONFIG_DIR ?? join(process.env.XDG_CONFIG_HOME ?? join(homedir(), ".config"), "ai-runtime-kit");
}

function renderAirkitHelp() {
  return `Usage: airkit <command> [options]

Commands:
  list [--visibility all|public|internal]
  init --profile <name> [--write] [--force] [--config-dir <dir>]
  update --profile <name> [--write] [--config-dir <dir>] [--preview-dir <dir>]
  doctor [--profile <name>] [--config-dir <dir>]
  render ccr --profile <name> [--out <path>]
  render shell --profile <name> [--out <path>]
  airclaude [auto|pro] [options] [-- <claude-args>]
  export-oss --out <dir>

Options:
  -h, --help    Show this help.

Examples:
  airkit list
  airkit init --profile openai-compatible-example
  airkit doctor --profile openai-compatible-example
  airkit airclaude pro --dry-run
`;
}

function renderAirclaudeHelp() {
  return `Usage: airclaude [auto|pro] [options] [-- <claude-args>]

Modes:
  auto          Use the profile's default low-friction routing.
  pro           Apply the profile's stronger routing overlay.

Options:
  --profile <name>       Select a launch-capable profile.
  --config-dir <dir>     Use a custom ai-runtime-kit config directory.
  --mode <auto|pro>      Select a mode without positional syntax.
  --dry-run              Render and report the launch plan without writing or launching.
  --doctor               Run launch preflight checks without launching.
  --repair-restore       Repair persisted Claude Code session model metadata and exit.
  -h, --help             Show this help.

Examples:
  airclaude
  airclaude pro
  airclaude --doctor
  airclaude --repair-restore
  airclaude -- --dangerously-skip-permissions
`;
}

function renderInstallPlan(plan) {
  const action = plan.write ? "Wrote" : "Dry run";
  const fileLines = [
    `- CCR config: ${plan.files.ccrConfig}`,
    `- Shell snippet: ${plan.files.shellSnippet}`,
    ...plan.files.managedFiles.map((file) => `- ${file.label}: ${file.path}`),
  ];

  return `${action} airkit profile: ${plan.profile.name}

Files:
${fileLines.join("\n")}

Next steps:
${plan.nextSteps.map((step) => `- ${step}`).join("\n")}

${plan.write ? "" : "Re-run with --write to create these files.\n"}`;
}

function renderUpdateResult(result) {
  const action = result.write ? "Wrote" : "Dry run";
  const targetLines = [
    `- ${result.files.ccrConfig.status} CCR config: ${result.files.ccrConfig.target}`,
    `- ${result.files.shellSnippet.status} shell snippet: ${result.files.shellSnippet.target}`,
    ...result.files.managedFiles.map((file) => `- ${file.status} ${file.label}: ${file.target}`),
  ];
  const previewLines = [
    `- CCR config: ${result.files.ccrConfig.preview}`,
    `- Shell snippet: ${result.files.shellSnippet.preview}`,
    ...result.files.managedFiles.map((file) => `- ${file.label}: ${file.preview}`),
  ];
  const diffLines = [
    `- CCR config: ${result.files.ccrConfig.diff}`,
    `- Shell snippet: ${result.files.shellSnippet.diff}`,
    ...result.files.managedFiles.map((file) => `- ${file.label}: ${file.diff}`),
  ];

  return `${action} update airkit profile: ${result.profile.name}

Targets:
${targetLines.join("\n")}

Preview files:
${previewLines.join("\n")}

Diff summary:
${diffLines.join("\n")}

${result.write ? "" : "Re-run with --write to overwrite stale or missing target files.\n"}`;
}

function renderLaunchResult(result, options = {}) {
  const action = options.doctor ? "Doctor" : options.dryRun || !result.write ? "Dry run" : "Launched";
  const fileLines = [
    `- ${result.files.ccrConfig.status} CCR config: ${result.files.ccrConfig.target}`,
    `- ${result.files.shellSnippet.status} shell snippet: ${result.files.shellSnippet.target}`,
    ...result.files.managedFiles.map((file) => `- ${file.status} ${file.label}: ${file.target}`),
  ];
  const runtimeLines = result.runtime
    ? [
        `- ${result.runtime.ccr.ok ? "ok" : "fail"} CCR: ${result.runtime.ccr.command}`,
        `- ${result.runtime.launch.ok ? "ok" : "fail"} launch command: ${result.runtime.launch.command}`,
      ]
    : [];

  return `${action} airclaude profile: ${result.profile.name}
mode: ${result.mode}

Routes:
- default: ${result.ccrConfig.Router?.default ?? "unset"}
- think: ${result.ccrConfig.Router?.think ?? "unset"}
- longContext: ${result.ccrConfig.Router?.longContext ?? "unset"}
- background: ${result.ccrConfig.Router?.background ?? "unset"}
- webSearch: ${result.ccrConfig.Router?.webSearch ?? "unset"}

Files:
${fileLines.join("\n")}
- ${result.liveCcrConfig.status} live CCR config: ${result.liveCcrConfig.path}

Runtime:
${runtimeLines.join("\n") || "- skipped"}
${result.restoreRepair ? `\nRestore repair:\n${renderRestoreRepairSummary(result.restoreRepair)}` : ""}

Launch:
- ${result.launch.command} ${[...result.launch.args, ...result.launch.userArgs].map(quoteShell).join(" ")}
`;
}

function renderRestoreRepairResult(result) {
  return `Restore repair airclaude profile: ${result.profile.name}
restore model: ${result.model ?? "disabled"}
projects dir: ${result.projectsDir}
scanned files: ${result.scannedFiles}
repaired files: ${result.repairedFiles}
repaired lines: ${result.repairedLines}
${result.backups.length ? `backups: ${result.backups.length} (${result.backupsDir})` : "backups: 0"}
`;
}

function renderRestoreRepairSummary(result) {
  if (!result.enabled) return "- disabled";
  return [
    `- restore model: ${result.model}`,
    `- scanned files: ${result.scannedFiles}`,
    `- repaired files: ${result.repairedFiles}`,
    `- repaired lines: ${result.repairedLines}`,
    `- backups: ${result.backups.length}${result.backupsDir ? ` (${result.backupsDir})` : ""}`,
  ].join("\n");
}

function renderProfile(catalog, profileName, options = {}) {
  const profile = findProfile(catalog, profileName);
  const configDir = resolve(options.configDir ?? defaultConfigDir());

  return {
    ccrConfig: `${JSON.stringify(buildCcrConfig(catalog, profileName, { configDir }), null, 2)}\n`,
    shellSnippet: buildShellSnippet(catalog, profileName, options),
    managedFiles: renderManagedFiles(profile, { configDir }),
  };
}

function resolveLaunchConfig(profile, templateVars) {
  if (profile.launch) return withReusableRuntimeLessons(profile.launch);
  const wrapper = profile.shell?.wrappers?.[0];
  if (wrapper) {
    return withReusableRuntimeLessons({
      binary: wrapper.command,
      args: wrapper.args ?? [],
      env: wrapper.env ?? {},
      defaultMode: "auto",
      modes: { auto: {} },
    });
  }
  return withReusableRuntimeLessons({
    binary: "ccr",
    args: ["code"],
    env: { CCR_PROFILE: "{{profileName}}" },
    defaultMode: "auto",
    modes: { auto: {} },
  });
}

function withReusableRuntimeLessons(launch) {
  const next = structuredClone(launch);
  if (!shouldAppendReusableRuntimeLessons(next.binary)) return next;
  next.args = mergeAppendSystemPrompt(next.args ?? [], reusableRuntimeLessonsPrompt);
  return next;
}

function shouldAppendReusableRuntimeLessons(binary) {
  const commandName = basename(String(binary ?? "").trim().split(/\s+/)[0] || "");
  return commandName === "claude" || commandName === "cclaude";
}

function mergeAppendSystemPrompt(args, prompt) {
  const next = [...args];
  const index = next.findIndex((arg) => arg === "--append-system-prompt");
  if (index >= 0 && typeof next[index + 1] === "string") {
    next[index + 1] = `${next[index + 1]} ${prompt}`;
  } else {
    next.push("--append-system-prompt", prompt);
  }
  return next;
}

function appendLaunchRuntimePrompts(args, binary, mode, ccrConfig, restore) {
  if (!shouldAppendReusableRuntimeLessons(binary)) return args;
  return appendRuntimePrompts(args, [airclaudeRoutingPrompt(mode, ccrConfig, restore)]);
}

function appendRuntimePrompts(args, prompts) {
  return prompts
    .filter((prompt) => typeof prompt === "string" && prompt.length > 0)
    .reduce((next, prompt) => mergeAppendSystemPrompt(next, prompt), args);
}

function resolveLaunchMode(profile, launch, requestedMode) {
  const mode = requestedMode ?? launch.defaultMode ?? "auto";
  const modes = launch.modes ?? { auto: {} };
  if (!Object.hasOwn(modes, mode)) {
    throw new Error(`profile "${profile.name}" does not define launch mode "${mode}"`);
  }
  return mode;
}

function applyLaunchModeOverlay(ccrConfig, profile, mode, templateVars) {
  const overlay = profile.launch?.modes?.[mode]?.ccr;
  if (!overlay) return ccrConfig;
  return mergeDeep(ccrConfig, renderTemplateValue(overlay, templateVars));
}

function launchTemplateVars(profile, configDir, mode, ccrConfig, restore) {
  const vars = {
    ...profileTemplateVars(profile, configDir),
    launchMode: mode,
    restoreModel: restore?.model ?? "",
    statuslineLabel: statuslineLabel(mode, ccrConfig),
  };

  for (const [key, route] of Object.entries(ccrConfig.Router ?? {})) {
    if (typeof route !== "string") continue;
    const routeKey = `route${toPascalCase(key)}`;
    const { provider, model } = splitRoute(route);
    vars[routeKey] = route;
    vars[`${routeKey}Provider`] = provider;
    vars[`${routeKey}Model`] = model;
  }

  return vars;
}

function airclaudeLaunchEnv(catalog, profile, mode, ccrConfig, restore) {
  const env = {
    AIRCLAUDE_PROFILE: profile.name,
    AIRCLAUDE_MODE: mode,
    AIRCLAUDE_STATUSLINE_LABEL: statuslineLabel(mode, ccrConfig),
    AIRCLAUDE_RESTORE_MODEL: restore?.model ?? "",
    CLAUDE_STATUSLINE_CACHE_DIR: join(homedir(), ".claude", "cache", "airclaude", profile.name, mode),
    // Claude Code sources the user's zsh snapshot in its non-interactive command shells. A
    // Powerlevel10k instant prompt there re-evals its git/dir segments and spams
    // "(eval): command not found: git/head/awk/dirname/basename". Quiet it for the launched
    // process only; the user's interactive P10k prompt and .zshrc are untouched.
    POWERLEVEL9K_INSTANT_PROMPT: "off",
  };

  const statuslineInputPrice = routeInputPrice(catalog, profile, ccrConfig.Router?.default);
  if (statuslineInputPrice !== null) {
    env.AIRCLAUDE_STATUSLINE_INPUT_PRICE_PER_MILLION = String(statuslineInputPrice);
  }

  for (const [key, route] of Object.entries(ccrConfig.Router ?? {})) {
    if (typeof route !== "string") continue;
    const envKey = `AIRCLAUDE_ROUTE_${toEnvKey(key)}`;
    const { provider, model } = splitRoute(route);
    env[envKey] = route;
    env[`${envKey}_PROVIDER`] = provider;
    env[`${envKey}_MODEL`] = model;
  }

  return env;
}

function routeInputPrice(catalog, profile, route) {
  if (typeof route !== "string") return null;
  const { provider, model } = splitRoute(route);
  return profileInputPrice(profile, provider, model) ?? catalogInputPrice(catalog, provider, model);
}

function profileInputPrice(profile, provider, model) {
  const pricing = profile.statusline?.modelPricingUsdPer1M ?? profile.statusline?.pricingUsdPer1M;
  if (!pricing || typeof pricing !== "object") return null;

  return inputPriceFromValue(pricing[`${provider},${model}`] ?? pricing[model] ?? pricing[`${provider}/${model}`]);
}

function catalogInputPrice(catalog, provider, model) {
  const providers = catalog.modelCatalog?.providers;
  if (!Array.isArray(providers)) return null;

  for (const providerEntry of providers) {
    for (const modelEntry of providerEntry.models ?? []) {
      if (!modelMatches(provider, model, providerEntry, modelEntry)) continue;
      const price = inputPriceFromValue(modelEntry.pricingUsdPer1M);
      if (price !== null) return price;
    }
  }

  return null;
}

function modelMatches(provider, model, providerEntry, modelEntry) {
  const candidates = new Set([
    modelEntry.id,
    modelEntry.litellm,
    ...(Array.isArray(modelEntry.aliases) ? modelEntry.aliases : []),
  ].filter(Boolean));

  if (provider) {
    candidates.add(`${provider}/${model}`);
    candidates.add(`${provider},${model}`);
  }
  if (providerEntry.id) candidates.add(`${providerEntry.id}/${model}`);
  if (providerEntry.litellmProvider) candidates.add(`${providerEntry.litellmProvider}/${model}`);

  return candidates.has(model);
}

function inputPriceFromValue(value) {
  if (typeof value === "number" && Number.isFinite(value) && value > 0) return value;
  if (!value || typeof value !== "object") return null;

  const input = Number(value.input ?? value.inputCacheMiss);
  return Number.isFinite(input) && input > 0 ? input : null;
}

function airclaudeRoutingPrompt(mode, ccrConfig, restore) {
  if (!ccrConfig?.Router || typeof ccrConfig.Router !== "object") return "";

  const routeLines = sortedRouterEntries(ccrConfig.Router).map(([key, route]) => {
    const { model } = splitRoute(route);
    return `- ${key}: ${route} (model ${model})`;
  });

  return [
    "AirClaude active routing:",
    `- mode: ${mode}`,
    "- AirClaude mode is routing mode, not Claude Code permission mode.",
    ...routeLines,
    restore?.model
      ? `- Claude restore/display model is compatibility metadata only: ${restore.model}`
      : "- Claude restore/display model is compatibility metadata only.",
    "- Do not infer the active provider route from Claude Code's displayed model name.",
    "- background/tool-heavy work may use the background route when the runtime/router selects it.",
    "- When compacting, restoring, summarizing, or reporting status, preserve AirClaude mode and provider routes separately from Claude-compatible display metadata.",
  ].join(" ");
}

function sortedRouterEntries(router) {
  const preferred = ["default", "think", "longContext", "background", "webSearch"];
  const entries = Object.entries(router)
    .filter(([, route]) => typeof route === "string");
  const byKey = new Map(entries);
  const sorted = preferred
    .filter((key) => byKey.has(key))
    .map((key) => [key, byKey.get(key)]);

  for (const [key, route] of entries) {
    if (!preferred.includes(key)) sorted.push([key, route]);
  }

  return sorted;
}

function statuslineLabel(mode, ccrConfig) {
  const route = ccrConfig.Router?.default;
  if (typeof route !== "string") return `airclaude ${mode}`;
  return `airclaude ${mode} ${splitRoute(route).model}`;
}

function splitRoute(route) {
  const index = route.indexOf(",");
  if (index === -1) return { provider: "", model: route };
  return {
    provider: route.slice(0, index),
    model: route.slice(index + 1),
  };
}

function toPascalCase(value) {
  return String(value)
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .replace(/^[a-z]/, (match) => match.toUpperCase())
    .replace(/[A-Z]/g, (match) => ` ${match}`)
    .trim()
    .split(/\s+/)
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join("");
}

function toEnvKey(value) {
  return String(value)
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase();
}

function resolveRestoreRepairConfig(profile) {
  const model = profile.launch?.restore?.model;
  if (!model) return null;

  const replaceModels = new Set(profile.launch?.restore?.models ?? []);
  for (const provider of profile.ccr?.Providers ?? []) {
    for (const providerModel of provider.models ?? []) {
      replaceModels.add(providerModel);
      if (provider.name) replaceModels.add(`${provider.name},${providerModel}`);
    }
  }
  for (const routerModel of Object.values(profile.ccr?.Router ?? {})) {
    if (typeof routerModel === "string") replaceModels.add(routerModel);
  }
  replaceModels.delete(model);
  return { model, replaceModels };
}

function claudeRestoreProjectsDir() {
  return join(homedir(), ".claude", "projects");
}

async function listClaudeSessionFiles(root) {
  let entries;
  try {
    entries = await readdir(root, { withFileTypes: true });
  } catch (error) {
    if (error?.code === "ENOENT") return [];
    throw error;
  }

  const files = [];
  for (const entry of entries) {
    const path = join(root, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listClaudeSessionFiles(path)));
    } else if (entry.isFile() && entry.name.endsWith(".jsonl")) {
      files.push(path);
    }
  }
  return files.sort();
}

function repairClaudeSessionText(text, restore) {
  let repairedLines = 0;
  const lines = text.split("\n").map((line) => {
    if (!line) return line;

    let record;
    try {
      record = JSON.parse(line);
    } catch {
      return line;
    }

    if (!repairMessageModel(record, restore)) return line;
    repairedLines += 1;
    return JSON.stringify(record);
  });

  return { text: lines.join("\n"), repairedLines };
}

function repairMessageModel(record, restore) {
  const message = record?.message;
  if (!message || typeof message !== "object") return false;
  if (typeof message.model !== "string") return false;
  if (!restore.replaceModels.has(message.model)) return false;
  message.model = restore.model;
  return true;
}

function restoreBackupPath(backupsDir, projectsDir, file) {
  const relativePath = relative(projectsDir, file).replaceAll(/[\\/]+/g, "__");
  return join(backupsDir, `${relativePath}.bak`);
}

function timestampForPath() {
  return new Date().toISOString().replaceAll(/[:.]/g, "-");
}

function mergeDeep(base, overlay) {
  if (Array.isArray(base) || Array.isArray(overlay) || !isPlainObject(base) || !isPlainObject(overlay)) {
    return structuredClone(overlay);
  }
  const merged = structuredClone(base);
  for (const [key, value] of Object.entries(overlay)) {
    merged[key] = key in merged ? mergeDeep(merged[key], value) : structuredClone(value);
  }
  return merged;
}

function isPlainObject(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

async function planLaunchFiles(plan, rendered) {
  return {
    ccrConfig: await checkLaunchFile(plan.files.ccrConfig, rendered.ccrConfig, "CCR config"),
    shellSnippet: await checkLaunchFile(plan.files.shellSnippet, rendered.shellSnippet, "shell snippet"),
    managedFiles: await Promise.all(
      rendered.managedFiles.map((file) => checkLaunchFile(file.path, file.content, file.label)),
    ),
  };
}

async function checkLaunchFile(path, expected, label) {
  let actual;
  try {
    actual = await readFile(path, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") {
      return { status: "missing", label, target: path };
    }
    throw error;
  }
  return { status: actual === expected ? "current" : "stale", label, target: path };
}

async function writeLaunchFiles(plan, rendered) {
  await mkdir(dirname(plan.files.ccrConfig), { recursive: true });
  await mkdir(dirname(plan.files.shellSnippet), { recursive: true });
  await writeFile(plan.files.ccrConfig, rendered.ccrConfig);
  await writeFile(plan.files.shellSnippet, rendered.shellSnippet);
  for (const file of rendered.managedFiles) {
    await mkdir(dirname(file.path), { recursive: true });
    await writeFile(file.path, file.content);
  }
}

async function checkLaunchRuntime(plan, options = {}) {
  const commandExists = options.commandExists ?? commandExistsOnPath;
  const runCommand = options.runCommand ?? runCommandSync;
  const env = options.env ?? process.env;
  const timeoutMs = options.commandTimeoutMs ?? 30000;
  const ccrExists = await commandExists("ccr");
  const launchExists = await commandExists(plan.launch.command);
  const runtime = {
    ccr: ccrExists ? { ok: true, command: "ccr" } : { ok: false, command: "ccr", reason: "missing command: ccr" },
    launch: launchExists
      ? { ok: true, command: plan.launch.command }
      : { ok: false, command: plan.launch.command, reason: `missing command: ${plan.launch.command}` },
  };
  if (!runtime.ccr.ok || options.dryRun || options.doctor) return runtime;

  const authEnv = await resolveCcrAuthEnv(plan, { commandExists, env, runCommand, timeoutMs });
  if (!authEnv.ok) {
    runtime.ccr = { ok: false, command: "ccr", reason: authEnv.reason };
    return runtime;
  }

  const restart = await runCommand("ccr", ["restart"], { env: { ...env, ...authEnv.env }, timeoutMs });
  if (!restart.ok) {
    runtime.ccr = {
      ok: false,
      command: "ccr",
      reason: `ccr restart failed${restart.stderr ? `: ${restart.stderr}` : ""}`,
    };
    return runtime;
  }

  const activate = await runCommand("ccr", ["activate"], { timeoutMs });
  if (!activate.ok) {
    runtime.ccr = {
      ok: false,
      command: "ccr",
      reason: `ccr activate failed${activate.stderr ? `: ${activate.stderr}` : ""}`,
    };
    return runtime;
  }
  runtime.ccr.env = parseShellExports(activate.stdout);
  return runtime;
}

async function resolveCcrAuthEnv(plan, { commandExists, env, runCommand, timeoutMs }) {
  const existingToken = env.ANTHROPIC_AUTH_TOKEN;
  if (existingToken && !existingToken.startsWith("op://")) {
    return { ok: true, env: { ANTHROPIC_AUTH_TOKEN: existingToken } };
  }

  const ref =
    env.CCR_ANTHROPIC_AUTH_TOKEN_OP_REF ??
    env.ANTHROPIC_AUTH_TOKEN_OP_REF_DEFAULT ??
    env.ANTHROPIC_AUTH_TOKEN_OP_REF ??
    plan.credential.ccrTokenOpRef;
  if (!ref) return { ok: true, env: {} };
  if (!(await commandExists("op"))) {
    return { ok: false, reason: `op not found; cannot resolve ${ref}` };
  }

  const token = await runCommand("op", ["read", ref, "--no-newline"], { env, timeoutMs });
  if (!token.ok) {
    return { ok: false, reason: `unable to read ${ref} from 1Password; run op signin and retry` };
  }
  return { ok: true, env: { ANTHROPIC_AUTH_TOKEN: token.stdout } };
}

function parseShellExports(source = "") {
  const env = {};
  for (const line of source.split("\n")) {
    const match = line.match(/^export\s+([A-Za-z_][A-Za-z0-9_]*)=(?:"([^"]*)"|'([^']*)'|(.*))$/);
    if (!match) continue;
    env[match[1]] = match[2] ?? match[3] ?? match[4] ?? "";
  }
  return env;
}

const bundledTransformersDir = join(repoRoot, "transformers");

function bundledTransformerNames(profile) {
  const names = new Set();
  const collect = (use) => {
    for (const entry of use ?? []) {
      const name = Array.isArray(entry) ? entry[0] : entry;
      if (typeof name === "string") names.add(name);
    }
  };
  for (const provider of profile.ccr?.Providers ?? []) {
    const transformer = provider.transformer;
    if (!transformer || typeof transformer !== "object") continue;
    collect(transformer.use);
    for (const [key, value] of Object.entries(transformer)) {
      if (key !== "use" && value && typeof value === "object") collect(value.use);
    }
  }
  return names;
}

function renderManagedFiles(profile, options = {}) {
  const configDir = resolve(options.configDir ?? defaultConfigDir());
  const vars = profileTemplateVars(profile, configDir);
  const explicit = (profile.managedFiles ?? []).map((file) => ({
    label: file.label ?? `managed file ${file.path}`,
    path: resolve(configDir, file.path),
    relativePath: file.path,
    content: renderTemplateValue(file.content, vars),
  }));

  const declared = new Set(explicit.map((file) => file.relativePath));
  const bundled = [];
  for (const name of bundledTransformerNames(profile)) {
    const source = join(bundledTransformersDir, `${name}.cjs`);
    const relativePath = `ccr/transformers/${name}.js`;
    if (declared.has(relativePath) || !existsSync(source)) continue;
    bundled.push({
      label: `bundled transformer ${name}`,
      path: resolve(configDir, relativePath),
      relativePath,
      content: renderTemplateValue(readFileSync(source, "utf8"), vars),
    });
  }

  return [...explicit, ...bundled];
}

async function writeTextFile(path, content, { force }) {
  if (!force && (await fileExists(path))) {
    throw new Error(`${path} already exists; pass --force to overwrite`);
  }
  await writeFile(path, content);
}

async function checkRenderedFile(path, expected, label) {
  let actual;
  try {
    actual = await readFile(path, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") {
      return { ok: false, label, path, reason: `missing ${label}: ${path}` };
    }
    throw error;
  }

  if (actual !== expected) {
    return { ok: false, label, path, reason: `stale ${label}: ${path}` };
  }
  return { ok: true, label, path };
}

async function planUpdateFile(target, preview, expected, label) {
  let actual;
  try {
    actual = await readFile(target, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") {
      return { status: "missing", label, target, preview, diff: `missing ${label}; would create` };
    }
    throw error;
  }

  if (actual === expected) {
    return { status: "current", label, target, preview, diff: "no changes" };
  }

  return { status: "stale", label, target, preview, diff: describeTextDiff(actual, expected) };
}

function describeTextDiff(actual, expected) {
  const actualLines = actual.split("\n");
  const expectedLines = expected.split("\n");
  const lineCount = Math.max(actualLines.length, expectedLines.length);

  for (let index = 0; index < lineCount; index += 1) {
    if (actualLines[index] !== expectedLines[index]) {
      return `first difference at line ${index + 1}`;
    }
  }

  return "content differs";
}

function renderDoctorResult(result) {
  const lines = [
    `profile: ${result.profile.name}`,
    `${result.files.ccrConfig.ok ? "ok" : "fail"} CCR config: ${result.files.ccrConfig.path}`,
    `${result.files.shellSnippet.ok ? "ok" : "fail"} shell snippet: ${result.files.shellSnippet.path}`,
    ...result.files.managedFiles.map(
      (file) => `${file.ok ? "ok" : "fail"} ${file.label ?? "managed file"}: ${file.path}`,
    ),
    `${statusOf(result.runtime.ccr)} CCR availability: ${result.runtime.ccr.command}`,
    `${statusOf(result.runtime.shellSource)} shell source: ${result.runtime.shellSource.path}`,
  ];
  for (const failure of result.failures) {
    lines.push(`- ${failure}`);
  }
  return `${lines.join("\n")}\n`;
}

async function checkCcrAvailability(profile, commandExists) {
  if (!profile.ccr) {
    return { ok: true, skipped: true, command: "ccr" };
  }
  if (await commandExists("ccr")) {
    return { ok: true, command: "ccr" };
  }
  return { ok: false, command: "ccr", reason: "missing command: ccr" };
}

async function checkShellSourceability(path, profile, sourceSnippet) {
  const result = await sourceSnippet(path, shellFunctionNames(profile));
  if (result.ok) {
    return { ok: true, path };
  }

  const detail = result.detail ? ` (${result.detail})` : "";
  return { ok: false, path, reason: `shell snippet is not sourceable: ${path}${detail}` };
}

function commandExistsOnPath(command) {
  const result = spawnSync("sh", ["-c", 'command -v "$1" >/dev/null 2>&1', "airkit-command-check", command], {
    stdio: "ignore",
  });
  return result.status === 0;
}

function runCommandSync(command, args = [], options = {}) {
  const result = spawnSync(command, args, {
    encoding: "utf8",
    env: { ...process.env, ...(options.env ?? {}) },
    timeout: options.timeoutMs ?? 30000,
  });
  const stderr = [result.stderr?.trim(), result.error?.message].filter(Boolean).join("\n");

  return {
    ok: result.status === 0,
    status: result.status,
    stdout: result.stdout?.trim() ?? "",
    stderr,
  };
}

function spawnCommandSync(command, args = [], options = {}) {
  return spawnSync(command, args, {
    stdio: options.stdio ?? "inherit",
    env: { ...process.env, ...(options.env ?? {}) },
  });
}

function sourceShellSnippet(path, functionNames) {
  const script = 'source "$1" || exit $?; shift; for fn in "$@"; do typeset -f "$fn" >/dev/null || exit 1; done';
  const result = spawnSync("zsh", ["-fc", script, "airkit-source-check", path, ...functionNames], {
    encoding: "utf8",
  });
  if (result.error) {
    return { ok: false, detail: result.error.message };
  }
  if (result.status === 0) {
    return { ok: true };
  }

  const detail = [result.stderr?.trim(), result.stdout?.trim()].filter(Boolean).join("; ");
  return { ok: false, detail: detail || `zsh exited ${result.status}` };
}

function shellFunctionNames(profile) {
  const shell = profile.shell ?? {};
  return [shell.ccrStartFunction, ...(shell.wrappers ?? []).map((wrapper) => wrapper.name)].filter(Boolean);
}

function statusOf(check) {
  if (check.skipped) return "skip";
  return check.ok ? "ok" : "fail";
}

function profileTemplateVars(profile, configDir = defaultConfigDir()) {
  return {
    configDir: resolve(configDir),
    profileName: profile.name,
  };
}

function renderTemplateValue(value, vars) {
  if (typeof value === "string") {
    let rendered = value;
    for (const [key, replacement] of Object.entries(vars)) {
      rendered = rendered.replaceAll(`{{${key}}}`, replacement);
    }
    return rendered;
  }
  if (Array.isArray(value)) {
    return value.map((entry) => renderTemplateValue(entry, vars));
  }
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([key, entry]) => [key, renderTemplateValue(entry, vars)]));
  }
  return value;
}

async function fileExists(path) {
  try {
    await access(path);
    return true;
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    throw error;
  }
}

function claudeGuide() {
  const defaultProfile = "openai-compatible-example";

  return `# CLAUDE.md - ai-runtime-kit

## Agent Start Here

This repo is the public OSS for AI runtime profiles. The goal is a guided,
OpenCode-style install flow: inspect first, write only when the user passes
\`--write\`.

Run these from the repo root:

\`\`\`bash
node src/airkit.mjs --help
node src/airkit.mjs airclaude --help
node src/airkit.mjs airclaude --dry-run
node src/airkit.mjs airclaude pro --dry-run
node src/airkit.mjs list
node src/airkit.mjs init --profile ${defaultProfile}
node src/airkit.mjs init --profile ${defaultProfile} --write
node src/airkit.mjs doctor
\`\`\`

\`airclaude\` is the daily launch path. The management dry run prints every file
path it would create. Do not edit runtime files directly unless the user
explicitly asks for a manual repair.

## Product Boundary

- Keep runtime state out of git: Claude sessions, CCR daemon state, caches,
  login state, and secret values.
- Profiles may contain placeholders such as \`$ANTHROPIC_AUTH_TOKEN\`.
- Public output must not contain private endpoints, company names,
  credential-manager item references, or personal/company tokens.

## Release Rules

For public changes:

\`\`\`bash
npm run verify
git push
\`\`\`

Do not add private endpoints, company names, credential-manager item references, or
personal/company tokens to this repository.
`;
}

if (isDirectEntrypoint()) {
  const entrypoint = basename(process.argv[1]);
  const argv = process.argv.slice(2);
  const runner = entrypoint === "airclaude" ? runAirclaudeCli : runCli;

  runner(argv)
    .then((exitCode) => {
      process.exitCode = exitCode;
    })
    .catch((error) => {
      console.error(`airkit: ${error.message}`);
      process.exitCode = 1;
    });
}

function isDirectEntrypoint() {
  if (!process.argv[1]) return false;
  try {
    return realpathSync(process.argv[1]) === fileURLToPath(import.meta.url);
  } catch {
    return false;
  }
}
